spring.application.name=REST_WebService_Java_Mongo

# Ajuster le niveau de log pour l'ensemble du projet
logging.level.root=INFO

# Afficher les logs DEBUG uniquement pour les classes
logging.level.fr.batou=DEBUG

# Enregistrer les logs dans un fichier
logging.file.name=api-clinique.log